config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :friendships
  resources :users, only: [:index]

  resources :conversations, only: [:index, :create] do
     resources :messages
  end

  root "friendships#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  sync :all
  
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  sync :all
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
end

app/models/user.rb
class User < ApplicationRecord
  sync :all
  
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friendships, :through => :inverse_friendships, :source => :user
  has_many :conversations, :foreign_key => :sender_id

  def unread(user, friend)
    converstaion = Conversation.between(user.id, friend.id).first
    if !converstaion.nil?
      converstaion.messages.where(read: false, user_id: friend.id).count
    else
      0
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)

      @friendship = current_user.friendships.build(:friend_id => params[:recipient_id])
      @friendship.save

      @friend = User.find(params[:recipient_id])
      @friendship = @friend.friendships.build(:friend_id => current_user.id)
      @friendship.save
    end

    redirect_to conversation_messages_path(@conversation)
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @friends = current_user.friends
  end

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_path
    else
      flash[:error] = "Unable to add friend"
      redirect_to root_path
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by(friend_id: params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to root_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  respond_to :html, :js

  def index
    @messages = @conversation.messages

    if @messages.length > 5
      @over_ten = true
      @messages = @messages[-5..-1]
    end

    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end

    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.each do |message|
          message.update(read: 'true')
        end
      end
    end

    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)

    if @message.save
      sync_new @message
    end
    redirect_to :back
  end

  def destroy
    @message = @conversation.messages.find(params[:id])
    @message.destroy
    sync_destroy @message

    redirect_to :back
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_sidebar.html.erb
<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
      <li class="<%= 'active' if current_page?(friendships_path) %>"><%= link_to 'Friends', friendships_path %></li>
      <li class="<%= 'active' if current_page?(conversations_path) %>"><%= link_to 'Histroy', conversations_path %></li>
    </ul>
</div>

app/views/conversations/index.html.erb
<div class="row">
  <%= render 'common/sidebar' %>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% @conversations.each do |conversation| %>
        <tr>
          <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
          <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <td><%= link_to recipient.name, conversation_messages_path(conversation)%></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/friendships/index.html.erb
<div class="row">
<%= render 'common/sidebar' %>
  <div class="col-md-9">
    <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Unread</th>
        <th>Conversation</th>
        <th>Set</th>
      </tr>
    </thead>
    <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.unread(current_user, friend) %></td>
        <td><%= link_to 'Conversation', conversations_path(:sender_id => current_user.id, :recipient_id => friend.id), method: :post , class: 'btn btn-primary' %></td>
        <td><%= link_to 'delete',friendship_path(friend), method: :delete, class: 'btn btn-danger', data: { confirm: "Delete this Friend?"}%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webchat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= include_sync_config %>

  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'WebChat', root_path, class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
          <li><a>Hi, <%= current_user.name %>!!</a></li>
          <li><%= link_to 'Friends', friendships_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message_row.html.erb
<li class="<%= message.user_id == current_user.id ? "right" : "left" %> clearfix">
  <span class="chat-img <%= message.user_id == current_user.id ? "pull-right" : "pull-left"%> ">
    <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
  </span>
  <div class="chat-body clearfix">
    <div class="header">
      <% user = User.find(message.user_id) %>
      <strong class="primary-font"><%= user.name %> </strong>
    </div>
    <p>
      <%= message.body %>
      <% unless current_user != user %>
      <%= link_to 'delete', conversation_message_path(@conversation, message), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </p>
  </div>
</li>

app/views/messages/index.html.erb
<% if @over_ten %>
<%= link_to 'Show Previous', '?m=all' %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="glyphicon glyphicon-comment"></span> Chat
      </div>
      <div class="panel-body" id="chat-body">
        <ul class="chat">
          <% @messages.each do |message| %>
          <% if message.body %>
          <li class="<%= message.user_id == current_user.id ? "right" : "left" %> clearfix">
            <span class="chat-img <%= message.user_id == current_user.id ? "pull-right" : "pull-left"%> ">
              <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
            </span>
            <div class="chat-body clearfix">
              <div class="header">
                <% user = User.find(message.user_id) %>
                <strong class="primary-font"><%= user.name %> </strong>
              </div>
              <p>
                <%= message.body %>
                <% unless current_user != user %>
                <%= link_to 'delete', conversation_message_path(@conversation, message), method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
              </p>
            </div>
          </li>
          <% end %>
          <% end %>
        </ul>
      </div>
      <div class="panel-footer">
        <%= form_for [@conversation, @message] do |f| %>
        <div class="input-group">
          <%= f.text_area :body, class: "form-control input-sm", placeholder: "Type your message here..." %>
          <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
          <span class="input-group-btn">
            <%= f.submit "Send", class: "btn btn-warning btn-sm", id: "btn-chat" %>
          </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Total Users</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Add</th>
          <th>Message</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <% unless current_user == user %>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
          <% if !current_user.friends.include?(user) %>
            <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
            <% else %>
            Your friend!
            <% end %>
            <td><%= link_to 'message me!', conversations_path(:sender_id => current_user.id, :recipient_id => user.id), method: :post %></td>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>